### ISSUE TITLE
libad9361-iio brew install with iio-scope

### ISSUE THREAD

**Issue by tfcollins** [tfcollins/homebrew-formulae#1]
Currently libad9361-iio brew install doesn't place header files currently so includes will break when compiling against it

**Comment by rgov** [comment]
This is probably resolved by #9. If you want, you could add a simple compilation to the `test` section. Here's an example for how we test that `libgnuradio-iio` headers exist and the library can be linked against.

```
    testpath/"test.cpp").write <<~EOS
       #include <iio/math.h>
       int main() {
         gr::iio::iio_math::make("0");
         return 0;
       }
     EOS
     system ENV.cxx, "-std=c++11", "-L#{lib}", "-lgnuradio-iio", "-o", "test", "test.cpp"
     system "./test"
```
