### ISSUE TITLE
No available formula or cask with the name "tfcollins/formulae/i-i-o-oscilloscope"

### ISSUE THREAD

**Issue by smdjeff** [tfcollins/homebrew-formulae#11]
landing here from  https://wiki.analog.com/resources/tools-software/linux-software/iio_oscilloscope

brew install --HEAD tfcollins/homebrew-formulae/i-i-o-oscilloscope
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "tfcollins/formulae/i-i-o-oscilloscope".

**Comment by tfcollins** [comment]
The recipe was renamed to iio_oscilloscope. We'll update the wiki.

**Comment by tfcollins** [comment]
Fixed.
