### ISSUE TITLE
Trouble building iio-oscilloscope on OS X10.14.6 and 11.4

### ISSUE THREAD

**Issue by erikwetterskog** [tfcollins/homebrew-formulae#14]
Hi there,

I'm working at a science center and we are trying to use ADALM-Pluto for some science activities junior high school students. I have massive troubles installing the software and building iio-oscilloscope, I've tried two different machines. At first, I had an error of the type when trying to install both iio-oscilloscope and soapyplutosdr (similar error for both "brews"):

==> Installing iio-oscilloscope from tfcollins/formulae
Error: Formulae found in multiple taps:
          * tfcollins/formulae/libiio
          * pothosware/pothos/libiio

I had to "brew untap -f pothosware/pothos/libiio"

After untapping I run into problems when using cmake. I'm not really that experienced with any of this, but the cmake command appears to have trouble with something called "gtkdatabox" or the like.

OS X 10.14.6 Machine (I've attached the log).

[02make.txt](https://github.com/tfcollins/homebrew-formulae/files/6740326/02make.txt)

**Comment by erikwetterskog** [comment]
And from the second machine (11.4), the errors given in the terminal appear similar.

[02.make.txt](https://github.com/tfcollins/homebrew-formulae/files/6740353/02.make.txt)

Let me know if you need anything else in terms of info/documentation. On this machine I installed libiio and libad from packages, on the 10.14.6 machine I did everything with brew. Below is a copy from the terminal. I tried using both --HEAD and without.

brew install tfcollins/formulae/iio-oscilloscope

==> Installing iio-oscilloscope from tfcollins/formulae
==> Downloading https://github.com/analogdevicesinc/iio-oscilloscope/archive/v0.
==> Downloading from https://codeload.github.com/analogdevicesinc/iio-oscillosco
                                -=O=-                     #    #   #   #      
==> cmake ..
==> make install
Last 15 lines from /Users/wettersk/Library/Logs/Homebrew/iio-oscilloscope/02.make:
                        GdkRGBA * color, guint size,
                        ^
In file included from /tmp/iio-oscilloscope-20210630-48942-hbah4z/iio-oscilloscope-0.11-master/osc.c:12:
/usr/local/Cellar/gtkdatabox/1.0.0/include/gtkdatabox_markers.h:149:10: error: unknown type name 'GdkRGBA'
                                            GdkRGBA * color, guint size,
                                            ^
/usr/local/Cellar/gtkdatabox/1.0.0/include/gtkdatabox_markers.h:164:4: error: unknown type name 'GdkRGBA'
                        GdkRGBA * color, guint size,
                        ^
12 errors generated.
make[2]: *** [CMakeFiles/osc.dir/osc.c.o] Error 1
12 errors generated.
make[2]: *** [CMakeFiles/osc.dir/oscplot.c.o] Error 1
make[1]: *** [CMakeFiles/osc.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/tfcollins/homebrew-formulae/issues

**Comment by tfcollins** [comment]
This is a known issue as reported here https://github.com/tfcollins/homebrew-formulae/issues/5

This comes from a breaking change from the upstream gtkdatabox package. Unfortunately, brew does not provide a consistent way of using older versions of a package so there is no workaround with the current codebase.

**Comment by tfcollins** [comment]
Closing this. Please see #5 for further discussion
