### ISSUE TITLE
Big Sur Build Failure

### ISSUE THREAD

**Issue by shreejithshanker** [tfcollins/homebrew-formulae#15]
Hi, 
I have been trying to build iio on my macOS big Sur (11.6.2). I was following thread #5 to work around the gtkdatabox issue. I have manually installed gtkdatabox 0.9.3.1 and tried the 'fix-gtk-upgrade' branch. I am stuck at the following error. 
```
$ HOMEBREW_NO_AUTO_UPDATE=1 brew install --HEAD tfcollins/homebrew-formulae/iio-oscilloscope --verbose
==> Downloading https://ghcr.io/v2/homebrew/core/gtkdatabox-prev1/manifests/0.9.3.1_1
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.3.9\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.6.2\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --header Accept:\ application/vnd.oci.image.index.v1\+json --header Authorization:\ Bearer\ QQ== --location --remote-time --output /Users/shreejiths/Library/Caches/Homebrew/downloads/23a988604d6c9865b4b038ebd695344d688da691e996115ecc7e361dbcce93f8--gtkdatabox-prev1-0.9.3.1_1.bottle_manifest.json.incomplete https://ghcr.io/v2/homebrew/core/gtkdatabox-prev1/manifests/0.9.3.1_1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Error: iio-oscilloscope: Failed to download resource "gtkdatabox-prev1_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/gtkdatabox-prev1/manifests/0.9.3.1_1
``

I have the following setup
``
brew --version
Homebrew 3.3.9
Homebrew/homebrew-core (git revision 09c4cc6; last commit 2022-01-09)
Homebrew/homebrew-cask (git revision 412fb64; last commit 2022-01-09)
``

Thanks, 
Shreejith

**Comment by tfcollins** [comment]
I think you are using the upstream gkdatabox which does not function with the current IIO-Scope.

Can you build as follows:
```
git clone -b fix-gtk-upgrade https://github.com/tfcollins/homebrew-formulae.git
cd homebrew-formulae
brew install --verbose --build-from-source ./gtkdatabox-prev1.rb
# if necessary: brew link --overwrite gtkdatabox-prev1
brew install --verbose --build-from-source ./iio-oscilloscope.rb
```

**Comment by shreejithshanker** [comment]
Thanks, Travis. That makes sense, let me try this and get back to you.

**Comment by shreejithshanker** [comment]
Hi Travis, 
It worked! Had to add ``HOMEBREW_NO_AUTO_UPDATE=1`` as a prefix since otherwise, brew automatically overwrites the formulae with the latest one. Also had to link it explicitly using the ``brew link``. 

On a side note, it does issue an error right at the start 
``Cask 'iio-oscilloscope' is unreadable: wrong constant name #<Class:0x00007fa8bb132c78>`` 
I hope this is not something to be worries about. 

Thanks for the help! .

**Comment by tfcollins** [comment]
I haven't seen this error. Are you just typing "osc" or some other command to launch IIO-Scope?

**Comment by shreejithshanker** [comment]
Hi Travis,
This was while using brew install, but despite the error, it builds fine. I was wondering if it points to something.

Best, 
Shreejith

**Comment by JoeyGlasserCS** [comment]
How would I do the same steps but for linux? I'm getting the same gtkdatabox error and I'm trying to rebuild from the old gtk file.

> I think you are using the upstream gkdatabox which does not function with the current IIO-Scope.
> 
> Can you build as follows:
> 
> ```
> git clone -b fix-gtk-upgrade https://github.com/tfcollins/homebrew-formulae.git
> cd homebrew-formulae
> brew install --verbose --build-from-source ./gtkdatabox-prev1.rb
> # if necessary: brew link --overwrite gtkdatabox-prev1
> brew install --verbose --build-from-source ./iio-oscilloscope.rb
> ```

**Comment by tfcollins** [comment]
@JoeyGlasserCS Linux isn't really supported. I would just build libgtkdatabox0_0.9.3.1-2 and libgtkdatabox-dev_0.9.3.1-2 from source or find pre-built packages for your OS
