### ISSUE TITLE
status?

### ISSUE THREAD

**Issue by dh1tw** [tfcollins/homebrew-formulae#4]
Hey,

I recently got a Pluto SDR. In order to get started with Pluto, I would like to poke around with IIOscilloscope. I'm using MacOS Mojave and manage my dependencies with homebrew.

From the Pluto Wiki I understand that `libad9361` and `libiio` have to be installed, before `i-i-o-oscilloscope` can be installed.

Unfortunately, I'm not able to install any of the libs with your formulas. Basically CMake is not able to sucessfully configure the projects.

Are the formulas still maintained? If so, have you been able to install the formualas? 

Thanks,
Tobias

**Comment by tfcollins** [comment]
The formulas are broken right now for libiio and libad9361. However, you can just install them through pkgs and the IIO-Scope formula will find them. See here: https://wiki.analog.com/sdrseminars

**Comment by dh1tw** [comment]
Thanks for the feedback @tfcollins. After installing libiio and libad9361 manually (as suggested with the provided pkgs) I was able to install i-i-o-oscilloscope through homebrew with your formula.
